### ISSUE TITLE
badzipfile

### ISSUE THREAD

**Issue by libing125** [vzhong/embeddings#3]
I run the following code

from embeddings import GloveEmbedding
GloveEmbedding('common_crawl_840', d_emb=300, show_progress=True)

with python3.6.5, embeddings==0.0.6

and get the error:
zipfile.BadZipFile: File is not a zip file

Thanks!

**Comment by EdwardBurgin** [comment]
Similar issue with the fasttext embeddings, raises BadZipFile: File is not a zip file

**Comment by XinChen1020** [comment]
Encountered the same issue with glove embeddings. Re-downloading it and placing it in ~/.embeddings/glove resolved the problem. Interestingly, when I deleted ~/.embeddings/glove and created `GloveEmbedding` from scratch (expecting it to fail), it worked as normal. Not sure if the issue was related to the initial downloading process.
